services:
  app:
    init: true
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_FIREBASE_EMULATOR_HOST=http://firebase-emulator:4000
    working_dir: /app
    volumes:
      - .:/app:cached
    command: [ "pnpm", "dev" ]

networks:
  default:
    driver: bridge
